//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookashka
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookashkaEntities : DbContext
    {
        public BookashkaEntities()
            : base("name=BookashkaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BiblSet> BiblSet { get; set; }
        public virtual DbSet<BookSet> BookSet { get; set; }
        public virtual DbSet<ChitSet> ChitSet { get; set; }
        public virtual DbSet<UchetSet> UchetSet { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
