//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookashka
{
    using System;
    using System.Collections.Generic;
    
    public partial class UchetSet
    {
        public int Id { get; set; }
        public int IdBibl { get; set; }
        public int IdChit { get; set; }
        public int IdBook { get; set; }
    
        public virtual BiblSet BiblSet { get; set; }
        public virtual BookSet BookSet { get; set; }
        public virtual ChitSet ChitSet { get; set; }
    }
}
